-- card_shops: 상세 페이지 정보(전화·영업시간·휴무·소개·태그)
ALTER TABLE "card_shops" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "card_shops" ADD COLUMN IF NOT EXISTS "hours" TEXT NOT NULL DEFAULT '';
ALTER TABLE "card_shops" ADD COLUMN IF NOT EXISTS "closedDays" TEXT NOT NULL DEFAULT '';
ALTER TABLE "card_shops" ADD COLUMN IF NOT EXISTS "intro" TEXT NOT NULL DEFAULT '';
ALTER TABLE "card_shops" ADD COLUMN IF NOT EXISTS "tags" TEXT NOT NULL DEFAULT '';
